### PR TITLE
Workflows

### PR DESCRIPTION
**Pull request by litman90**
The code was reformatted using black and flake8 with some exceptions that need some proper attention.

A workflow that checks for formatting using flake8 and runs pytest was implemented and it is working.
Additionally, the workflow includes calling i-pi, compiling the driver code, and running some examples.

I see it as a good starting point which makes it possible for everyone to contribute easily and to add more tests progressively.
Yet, many things would require a deeper discussion.

### CODE REVIEW

**Comment by mahrossi** [comment]
But checks are failing?

**Comment by litman90** [comment]
I fixed the errors. Karen, try to check the tests locally before pushing.

**Comment by mahrossi** [comment]
Hello, should I delete this pull request? The branch now has conflicts. Or resolve the conflicts and merge? The workflow already went to another branch.

**Comment by litman90** [comment]
This PR has valuable work regarding the formating. Let me solve the conflicts.

**Comment by litman90** [comment]
I have resolved the conflicts and activated flake8. This means that if this PR is accepted later PR will have to pass flake8 compliant.

**Comment by litman90** [comment]
I have run black and activated flake8.
I think before merging it would be nice if some people can have a look in order to spot something weird that may have happend with black autoformatting.  I couldn't find anything. So from my side it is ready to merge.

**Comment by litman90** [comment]
The conflicts after the sync are solved now.

**Pull request merged**
